eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:#http://localhost:8761/eureka/}

server:
  port: 8004

spring:
  datasource:
    url: jdbc:mysql://${mysql.host}/course_service_db?createDatabaseIfNotExist=true
    hikari:
      username: ${mysql.username}
      password: ${mysql.password}
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  profiles:
    active: ${BMS_PROFILE}
  config:
    import: configserver:${CONFIG_SERVER_URL:#http://localhost:8888}
  application:
    name: inventory-service
  rabbitmq:
    host: ${rabbitmq.host}
    port: ${rabbitmq.port}
    username: ${rabbitmq.username}
    password: ${rabbitmq.password}
    cart-inventory:
      queue:
        add-book-to-cart: ci-add-book-to-cart-queue
        remove-book-from-cart: ci-remove-book-from-cart-queue
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: ${redis.host}
      port: ${redis.port}
      password: ${redis.password}
      database: ${redis.database}
      jedis:
        pool:
          max-active: 10
          max-wait: -1ms
          max-idle: 10
          min-idle: 0

management:
  tracing:
    sampling:
      probability: 1.0

logging:
    pattern:
        level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"